#before_script:
#    - apt-get install build-essential python-dev libjpeg62-turbo-dev libfreetype6-dev zlib1g-dev

test:
    type: deploy
    script:
        - cd /srv/apetizer
        - source bin/activate
        - git pull
        - pip install -r requirements.txt
        - python manage.py test
        - deactivate