# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 13:09
from __future__ import unicode_literals

import apetizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apetizer', '0023_auto_20160113_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapath',
            name='data',
            field=models.TextField(blank=True, default=b'{}', null=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='subdomains',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apetizer.models.upload_to_resource),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apetizer.models.upload_to_media),
        ),
        migrations.AlterField(
            model_name='translation',
            name='label',
            field=models.CharField(blank=True, max_length=65),
        ),
    ]
